spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:notification-db}:5432/${DB_NAME:notification-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.codingshuttle.linkedin.*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 9040
  servlet:
      context-path: /notification