spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/notification-db
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
