spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:users-db}:5432/${DB_NAME:users-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: kljahgkh-iahgashg-asfgadgh-ahasfh-adhafdh-adhadhadhkhasgkhaskgh

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 9010
  servlet:
    context-path: /users

# docker run --name local-user-db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=user-db -p 5432:5432 -d postgres