apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: ambraj/users-service:v1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: password
          - name: DB_SERVICE
            value: users-db
          - name: DB_NAME
            value: users-db
        ports:
        - containerPort: 9010

---

apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  ports:
  - port: 80
    targetPort: 9010

  
