apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  USERS_PGDATA: /var/lib/postgresql/data/pgdata
  POSTS_PGDATA: /var/lib/postgresql/data/pgdata
  NOTIFICATION_PGDATA: /var/lib/postgresql/data/pgdata
