spring:
  application:
    name: connections-service
  neo4j:
    uri: ${SPRING_DATASOURCE_URL:bolt://localhost:7687}
    authentication:
      username: ${SPRING_DATASOURCE_USERNAME:neo4j}
      password: ${SPRING_DATASOURCE_PASSWORD:password}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083
  servlet:
    context-path: /connections

# eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
