spring:
  application:
    name: connections-service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 9030
  servlet:
    context-path: /connections