spring:
  application:
    name: connections-service
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: neoneoneo

server:
  port: 8083
  servlet:
    context-path: /connections

# eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
