spring:
  application:
    name: connections-service
  neo4j:
    uri: ${SPRING_DATASOURCE_URL:bolt://localhost:7687}
    authentication:
      username: ${SPRING_DATASOURCE_USERNAME:neo4j}
      password: ${SPRING_DATASOURCE_PASSWORD:password}

server:
  port: 8083
  servlet:
    context-path: /connections

# eureka client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
