name: LinkedIn CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: linkedin-app
  GKE_ZONE: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-gateway
          - users-service
          - posts-service
          - connections-service
          - notification-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: ${{ matrix.service }}
        run: |
          docker build -t ${{ matrix.service }}:latest .
          docker tag ${{ matrix.service }}:latest ambraj/${{ matrix.service }}:latest
          docker push ambraj/${{ matrix.service }}:latest

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: kubectl - Google Cloud GKE cluster.
#        uses: ameydev/gke-kubectl-action@master
#        env:
#          PROJECT_ID: ${{ env.PROJECT_ID }}
#          APPLICATION_CREDENTIALS: ${{ secrets.GK_SA_KEY }}
#          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
#          ZONE_NAME: ${{ env.GKE_ZONE }}
#        with:
#          args: apply -f k8s/
