spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/posts-db
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082