spring:
  application:
    name: posts-service
  datasource:
    url: jdbc:postgresql://${DB_SERVICE:posts-db}:5432/${DB_NAME:posts-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  aop:
    auto: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 9020
  servlet:
    context-path: /posts
