name: LinkedIn CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: linkedin-app
  GKE_ZONE: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-arch Docker images
        uses: docker/bake-action@v6
        with:
          files: infrastructure/docker/docker-bake.hcl
          push: true

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: kubectl - Google Cloud GKE cluster.
#        uses: ameydev/gke-kubectl-action@master
#        env:
#          PROJECT_ID: ${{ env.PROJECT_ID }}
#          APPLICATION_CREDENTIALS: ${{ secrets.GK_SA_KEY }}
#          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
#          ZONE_NAME: ${{ env.GKE_ZONE }}
#        with:
#          args: apply -f k8s/
